apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-1
  labels:
    test: resource-exhaustion
spec:
  restartPolicy: Never
  containers:
  - name: gpu-app
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      requests:
        nvidia.com/mig-2g.20gb: "1"
      limits:
        nvidia.com/mig-2g.20gb: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-2
  labels:
    test: resource-exhaustion
spec:
  restartPolicy: Never
  containers:
  - name: gpu-app
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      requests:
        nvidia.com/mig-2g.20gb: "1"
      limits:
        nvidia.com/mig-2g.20gb: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-3
  labels:
    test: resource-exhaustion
spec:
  restartPolicy: Never
  containers:
  - name: gpu-app
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      requests:
        nvidia.com/mig-2g.20gb: "1"
      limits:
        nvidia.com/mig-2g.20gb: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-4
  labels:
    test: resource-exhaustion
spec:
  restartPolicy: Never
  containers:
  - name: gpu-app
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      requests:
        nvidia.com/mig-2g.20gb: "1"
      limits:
        nvidia.com/mig-2g.20gb: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-5
  labels:
    test: resource-exhaustion
spec:
  restartPolicy: Never
  containers:
  - name: gpu-app
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      requests:
        nvidia.com/mig-2g.20gb: "1"
      limits:
        nvidia.com/mig-2g.20gb: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-6
  labels:
    test: resource-exhaustion
spec:
  restartPolicy: Never
  containers:
  - name: gpu-app
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      requests:
        nvidia.com/mig-2g.20gb: "1"
      limits:
        nvidia.com/mig-2g.20gb: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-7
  labels:
    test: resource-exhaustion
spec:
  restartPolicy: Never
  containers:
  - name: gpu-app
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      requests:
        nvidia.com/mig-2g.20gb: "1"
      limits:
        nvidia.com/mig-2g.20gb: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-8
  labels:
    test: resource-exhaustion
spec:
  restartPolicy: Never
  containers:
  - name: gpu-app
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      requests:
        nvidia.com/mig-2g.20gb: "1"
      limits:
        nvidia.com/mig-2g.20gb: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-9
  labels:
    test: resource-exhaustion
spec:
  restartPolicy: Never
  containers:
  - name: gpu-app
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      requests:
        nvidia.com/mig-2g.20gb: "1"
      limits:
        nvidia.com/mig-2g.20gb: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-10
  labels:
    test: resource-exhaustion
spec:
  restartPolicy: Never
  containers:
  - name: gpu-app
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      requests:
        nvidia.com/mig-2g.20gb: "1"
      limits:
        nvidia.com/mig-2g.20gb: "1"
